version: "3"
services:
  mysql:
    # Sakai requires the database to use UTF-8.
    command: --character-set-server=utf8 --max_allowed_packet=32505856
    restart: always
    environment:
      # See https://docs.docker.com/samples/library/mysql/#environment-variables
      MYSQL_DATABASE: sakai
      MYSQL_USER: sakai
      MYSQL_PASSWORD: sakaipass
      MYSQL_ROOT_PASSWORD: rootpass
    build:
      context: mysql
    ports:
      - "3308:3306"
  sakai:
    build: .
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql:3306
      DATABASE_NAME: sakai
      DATABASE_USER: sakai
      DATABASE_PASSWORD: sakaipass
    # image: hypothesis/sakai:latest
    ports:
      - "8080:8080"
